services:
  postgres:
    image: postgres:15
    container_name: postgresCont
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: rest_api_node_ts
      POSTGRES_USER: root
      POSTGRES_PASSWORD: develop2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      postgres_network:
        aliases:
          - postgres_host

networks:
  postgres_network:
    name: postgres_network
    driver: bridge

volumes:
  postgres_data:
